name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 24.2.1-alpine-3.15.0
          - erlang: 23.3.4.10-alpine-3.15.0
          - erlang: 22.2.1-alpine-3.12.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          make docker-setup DOCKER_OTP_VERSION=${{matrix.erlang}}

      - name: Test
        run: |
          make docker-test DOCKER_OTP_VERSION=${{matrix.erlang}}

      - name: Logs
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: ct-logs-${{matrix.erlang}}
          path: logs/*
